export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';

export const CART_NO_USER_ADD_ITEM_REQUEST = 'CART_NO_USER_ADD_ITEM_REQUEST';
export const CART_NO_USER_ADD_ITEM_SUCCESS = 'CART_NO_USER_ADD_ITEM_SUCCESS';

export const CART_UPDATE_ITEM_REQUEST = 'CART_UPDATE_ITEM_REQUEST';
export const CART_UPDATE_ITEM_SUCCESS = 'CART_UPDATE_ITEM_SUCCESS';
export const CART_UPDATE_ITEM_FAIL = 'CART_UPDATE_ITEM_FAIL';

export const CART_NO_USER_UPDATE_ITEM_REQUEST = 'CART_NO_USER_UPDATE_ITEM_REQUEST';
export const CART_NO_USER_UPDATE_ITEM_SUCCESS = 'CART_NO_USER_UPDATE_ITEM_SUCCESS';

export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST';
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS';
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL';

export const CART_NO_USER_REMOVE_ITEM_REQUEST = 'CART_NO_USER_REMOVE_ITEM_REQUEST';
export const CART_NO_USER_REMOVE_ITEM_SUCCESS = 'CART_NO_USER_REMOVE_ITEM_SUCCESS';

export const CART_ITEM_REQUEST = 'CART_ITEM_REQUEST';
export const CART_ITEM_SUCCESS = 'CART_ITEM_SUCCESS';
export const CART_ITEM_FAIL = 'CART_ITEM_FAIL';

export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';
export const CART_EMPTY_REQUEST = 'CART_EMPTY_REQUEST';

export const CART_ADD_IMAGE_CASE_ITEM_REQUEST = 'CART_ADD_IMAGE_CASE_ITEM_REQUEST';
export const CART_ADD_IMAGE_CASE_ITEM_SUCCESS = 'CART_SAVCART_ADD_IMAGE_CASE_ITEM_SUCCESSE_PAYMENT';
export const CART_ADD_IMAGE_CASE_ITEM_FAIL = 'CART_ADD_IMAGE_CASE_ITEM_FAIL';