export const ADMIN_COLLECTION_LIST_REQUEST = 'ADMIN_COLLECTION_LIST_REQUEST';
export const ADMIN_COLLECTION_LIST_SUCCESS = 'ADMIN_COLLECTION_LIST_SUCCESS';
export const ADMIN_COLLECTION_LIST_FAIL = 'ADMIN_COLLECTION_LIST_FAIL';

export const COLLECTION_LIST_REQUEST = 'COLLECTION_LIST_REQUEST';
export const COLLECTION_LIST_SUCCESS = 'COLLECTION_LIST_SUCCESS';
export const COLLECTION_LIST_FAIL = 'COLLECTION_LIST_FAIL';

export const COLLECTION_DETAILS_REQUEST = 'COLLECTION_DETAILS_REQUEST';
export const COLLECTION_DETAILS_SUCCESS = 'COLLECTION_DETAILS_SUCCESS';
export const COLLECTION_DETAILS_FAIL = 'COLLECTION_DETAILS_FAIL';

export const COLLECTION_SAVE_REQUEST = 'COLLECTION_SAVE_REQUEST';
export const COLLECTION_SAVE_SUCCESS = 'COLLECTION_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const COLLECTION_VISIBILITY_CHANGE_REQUEST = 'COLLECTION_VISIBILITY_CHANGE_REQUEST';
export const COLLECTION_VISIBILITY_CHANGE_SUCCESS = 'COLLECTION_VISIBILITY_CHANGE_SUCCESS';
export const COLLECTION_VISIBILITY_CHANGE_FAIL = 'COLLECTION_VISIBILITY_CHANGE_FAIL';

export const COLLECTION_RANDOM_LIST_REQUEST = 'COLLECTION_RANDOM_LIST_REQUEST';
export const COLLECTION_RANDOM_LIST_SUCCESS = 'COLLECTION_RANDOM_LIST_SUCCESS';
export const COLLECTION_RANDOM_LIST_FAIL = 'COLLECTION_RANDOM_LIST_FAIL';