export const SEND_REGISTER_COMFIRMATION_REQUEST = 'SEND_REGISTER_COMFIRMATION_REQUEST';
export const SEND_REGISTER_COMFIRMATION_SUCCESS = 'SEND_REGISTER_COMFIRMATION_SUCCESS';
export const SEND_REGISTER_COMFIRMATION_FAIL = 'SEND_REGISTER_COMFIRMATION_FAIL';

export const SEND_EMAIL_TO_CONTACT_REQUEST = 'SEND_EMAIL_TO_CONTACT_REQUEST';
export const SEND_EMAIL_TO_CONTACT_SUCCESS = 'SEND_EMAIL_TO_CONTACT_SUCCESS';
export const SEND_EMAIL_TO_CONTACT_FAIL = 'SEND_EMAIL_TO_CONTACT_FAIL';

export const SEND_EMAIL_FOR_NEWSLETTER_CONFIRM_REQUEST = 'SEND_EMAIL_FOR_NEWSLETTER_CONFIRM_REQUEST';
export const SEND_EMAIL_FOR_NEWSLETTER_CONFIRM_SUCCESS = 'SEND_EMAIL_FOR_NEWSLETTER_CONFIRM_SUCCESS';
export const SEND_EMAIL_FOR_NEWSLETTER_CONFIRM_FAIL = 'SEND_EMAIL_FOR_NEWSLETTER_CONFIRM_FAIL';

export const SEND_EMAIL_FOR_NEWSLETTER_DELETE_REQUEST = 'SEND_EMAIL_FOR_NEWSLETTER_DELETE_REQUEST';
export const SEND_EMAIL_FOR_NEWSLETTER_DELETE_SUCCESS = 'SEND_EMAIL_FOR_NEWSLETTER_DELETE_SUCCESS';
export const SEND_EMAIL_FOR_NEWSLETTER_DELETE_FAIL = 'SEND_EMAIL_FOR_NEWSLETTER_DELETE_FAIL';

export const SEND_EMAIL_TO_CONFIRM_ORDER_REQUEST = 'SEND_EMAIL_TO_CONFIRM_ORDER_REQUEST';
export const SEND_EMAIL_TO_CONFIRM_ORDER_SUCCESS = 'SEND_EMAIL_TO_CONFIRM_ORDER_SUCCESS';
export const SEND_EMAIL_TO_CONFIRM_ORDER_FAIL = 'SEND_EMAIL_TO_CONFIRM_ORDER_FAIL';

export const SEND_NEW_ORDER_EMAIL_REQUEST = 'SEND_NEW_ORDER_EMAIL_REQUEST';
export const SEND_NEW_ORDER_EMAIL_SUCCESS = 'SEND_NEW_ORDER_EMAIL_SUCCESS';
export const SEND_NEW_ORDER_EMAIL_FAIL = 'SEND_NEW_ORDER_EMAIL_FAIL';

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';
export const SEND_PASSWORD_RESET_FAIL = 'SEND_PASSWORD_RESET_FAIL';

export const UPDATE_PASSWORD_RESET_REQUEST = 'UPDATE_PASSWORD_RESET_REQUEST';
export const UPDATE_PASSWORD_RESET_SUCCESS = 'UPDATE_PASSWORD_RESET_SUCCESS';
export const UPDATE_PASSWORD_RESET_FAIL = 'UPDATE_PASSWORD_RESET_FAIL';

export const SEND_UPDATE_PASSWORD_CONFIRM_REQUEST = 'SEND_UPDATE_PASSWORD_CONFIRM_REQUEST';
export const SEND_UPDATE_PASSWORD_CONFIRM_SUCCESS = 'SEND_UPDATE_PASSWORD_CONFIRM_SUCCESS';
export const SEND_UPDATE_PASSWORD_CONFIRM_FAIL = 'SEND_UPDATE_PASSWORD_CONFIRM_FAIL';

export const SEND_ACCOUNT_DELETE_EMAIL_REQUEST = 'SEND_ACCOUNT_DELETE_EMAIL_REQUEST';
export const SEND_ACCOUNT_DELETE_EMAIL_SUCCESS = 'SEND_ACCOUNT_DELETE_EMAIL_SUCCESS';
export const SEND_ACCOUNT_DELETE_EMAIL_FAIL = 'SEND_ACCOUNT_DELETE_EMAIL_FAIL';