export const MODEL_LIST_REQUEST = 'MODEL_LIST_REQUEST';
export const MODEL_LIST_SUCCESS = 'MODEL_LIST_SUCCESS';
export const MODEL_LIST_FAIL = 'MODEL_LIST_FAIL';

export const PHONE_BRAND_LIST_REQUEST = 'PHONE_BRAND_LIST_REQUEST';
export const PHONE_BRAND_LIST_SUCCESS = 'PHONE_BRAND_LIST_SUCCESS';
export const PHONE_BRAND_LIST_FAIL = 'PHONE_BRAND_LIST_FAIL';

export const BRAND_INSERT_REQUEST = 'BRAND_INSERT_REQUEST';
export const BRAND_INSERT_SUCCESS = 'BRAND_INSERT_SUCCESS';
export const BRAND_INSERT_FAIL = 'BRAND_INSERT_FAIL';

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST';
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS';
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL';

export const MODEL_INSERT_REQUEST = 'MODEL_INSERT_REQUEST';
export const MODEL_INSERT_SUCCESS = 'MODEL_INSERT_SUCCESS';
export const MODEL_INSERT_FAIL = 'MODEL_INSERT_FAIL';

export const MODEL_DELETE_REQUEST = 'MODEL_DELETE_REQUEST';
export const MODEL_DELETE_SUCCESS = 'MODEL_DELETE_SUCCESS';
export const MODEL_DELETE_FAIL = 'MODEL_DELETE_FAIL';

export const PHONE_MODEL_LIST_REQUEST = 'PHONE_MODEL_LIST_REQUEST';
export const PHONE_MODEL_LIST_SUCCESS = 'PHONE_MODEL_LIST_SUCCESS';
export const PHONE_MODEL_LIST_FAIL = 'PHONE_MODEL_LIST_FAIL';