export const ORDER_ADD_REQUEST = 'ORDER_ADD_REQUEST';
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL';

export const ORDER_CHANGE_STATUS_REQUEST = 'ORDER_CHANGE_STATUS_REQUEST';
export const ORDER_CHANGE_STATUS_SUCCESS = 'ORDER_CHANGE_STATUS_SUCCESS';
export const ORDER_CHANGE_STATUS_FAIL = 'ORDER_CHANGE_STATUS_FAIL';

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST';
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS';
export const ORDER_UPDATE_STATUS_FAIL = 'ORDER_UPDATE_STATUS_FAIL';

export const ORDER_DETAILS_CHANGE_REQUEST = 'ORDER_DETAILS_CHANGE_REQUEST';
export const ORDER_DETAILS_CHANGE_SUCCESS = 'ORDER_DETAILS_CHANGE_SUCCESS';
export const ORDER_DETAILS_CHANGE_FAIL = 'ORDER_DETAILS_CHANGE_FAIL';

export const ORDER_CHARGER_ADDRESS_UPDATE_REQUEST = 'ORDER_CHARGER_ADDRESS_UPDATE_REQUEST';
export const ORDER_CHARGER_ADDRESS_UPDATE_SUCCESS = 'ORDER_CHARGER_ADDRESS_UPDATE_SUCCESS';
export const ORDER_CHARGER_ADDRESS_UPDATE_FAIL = 'ORDER_CHARGER_ADDRESS_UPDATE_FAIL';

export const ORDER_SHIPPING_ADDRESS_UPDATE_REQUEST = 'ORDER_SHIPPING_ADDRESS_UPDATE_REQUEST';
export const ORDER_SHIPPING_ADDRESS_UPDATE_SUCCESS = 'ORDER_SHIPPING_ADDRESS_UPDATE_SUCCESS';
export const ORDER_SHIPPING_ADDRESS_UPDATE_FAIL = 'ORDER_SHIPPING_ADDRESS_UPDATE_FAIL';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

export const ORDER_DELETED_ITEM_REQUEST = 'ORDER_DELETED_ITEM_REQUEST';
export const ORDER_DELETED_ITEM_SUCCESS = 'ORDER_DELETED_ITEM_SUCCESS';
export const ORDER_DELETED_ITEM_FAIL = 'ORDER_DELETED_ITEM_FAIL';

export const CUSTOMER_ORDER_LIST_REQUEST = 'CUSTOMER_ORDER_LIST_REQUEST';
export const CUSTOMER_ORDER_LIST_SUCCESS = 'CUSTOMER_ORDER_LIST_SUCCESS';
export const CUSTOMER_ORDER_LIST_FAIL = 'CUSTOMER_ORDER_LIST_FAIL';

export const CUSTOMER_ORDER_DETAIL_REQUEST = 'CUSTOMER_ORDER_DETAIL_REQUEST';
export const CUSTOMER_ORDER_DETAIL_SUCCESS = 'CUSTOMER_ORDER_DETAIL_SUCCESS';
export const CUSTOMER_ORDER_DETAIL_FAIL = 'CUSTOMER_ORDER_DETAIL_FAIL';

export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAIL = 'GET_ORDER_HISTORY_FAIL';