export const SENDING_METHODS_LIST_REQUEST = 'SENDING_METHODS_LIST_REQUEST';
export const SENDING_METHODS_LIST_SUCCESS = 'SENDING_METHODS_LIST_SUCCESS';
export const SENDING_METHODS_LIST_FAIL = 'SENDING_METHODS_LIST_FAIL';

export const PAYMENT_METHODS_LIST_REQUEST = 'PAYMENT_METHODS_LIST_REQUEST';
export const PAYMENT_METHODS_LIST_SUCCESS = 'PAYMENT_METHODS_LIST_SUCCESS';
export const PAYMENT_METHODS_LIST_FAIL = 'PAYMENT_METHODS_LIST_FAIL';