export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_MOST_VIEWED_REQUEST = 'PRODUCT_MOST_VIEWED_REQUEST';
export const PRODUCT_MOST_VIEWED_SUCCESS = 'PRODUCT_MOST_VIEWED_SUCCESS';
export const PRODUCT_MOST_VIEWED_FAIL = 'PRODUCT_MOST_VIEWED_FAIL';

export const SEARCH_FOR_ITEMS_REQUEST = 'SEARCH_FOR_ITEMS_REQUEST';
export const SEARCH_FOR_ITEMS_SUCCESS = 'SEARCH_FOR_ITEMS_SUCCESS';
export const SEARCH_FOR_ITEMS_FAIL = 'SEARCH_FOR_ITEMS_FAIL';

export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';

export const SELECT_ITEMS_PER_PAGE = 'SELECT_ITEMS_PER_PAGE';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';

export const RESET_SEARCH_FILTERS = 'RESET_SEARCH_FILTERS';

export const MANUFACTURES_LIST_REQUEST = 'MANUFACTURES_LIST_REQUEST';
export const MANUFACTURES_LIST_SUCCESS = 'MANUFACTURES_LIST_SUCCESS';
export const MANUFACTURES_LIST_FAIL = 'MANUFACTURES_LIST_FAIL';

export const MANUFACTURER_INSERT_REQUEST = 'MANUFACTURER_INSERT_REQUEST';
export const MANUFACTURER_INSERT_SUCCESS = 'MANUFACTURER_INSERT_SUCCESS';
export const MANUFACTURER_INSERT_FAIL = 'MANUFACTURER_INSERT_FAIL';

export const MANUFACTURER_DELETE_REQUEST = 'MANUFACTURER_DELETE_REQUEST';
export const MANUFACTURER_DELETE_SUCCESS = 'MANUFACTURER_DELETE_SUCCESS';
export const MANUFACTURER_DELETE_FAIL = 'MANUFACTURER_DELETE_FAIL';

export const SUPPLIERS_INSERT_REQUEST = 'SUPPLIERS_INSERT_REQUEST';
export const SUPPLIERS_INSERT_SUCCESS = 'SUPPLIERS_INSERT_SUCCESS';
export const SUPPLIERS_INSERT_FAIL = 'SUPPLIERS_INSERT_FAIL';

export const SUPPLIERS_DELETE_REQUEST = 'SUPPLIERS_DELETE_REQUEST';
export const SUPPLIERS_DELETE_SUCCESS = 'SUPPLIERS_DELETE_SUCCESS';
export const SUPPLIERS_DELETE_FAIL = 'SUPPLIERS_DELETE_FAIL';

export const FEATURE_TITLE_LIST_REQUEST = 'FEATURE_TITLE_LIST_REQUEST';
export const FEATURE_TITLE_LIST_SUCCESS = 'FEATURE_TITLE_LIST_SUCCESS';
export const FEATURE_TITLE_LIST_FAIL = 'FEATURE_TITLE_LIST_FAIL';

export const FEATURE_TITLE_INSERT_REQUEST = 'FEATURE_TITLE_INSERT_REQUEST';
export const FEATURE_TITLE_INSERT_SUCCESS = 'FEATURE_TITLE_INSERT_SUCCESS';
export const FEATURE_TITLE_INSERT_FAIL = 'FEATURE_TITLE_INSERT_FAIL';

export const FEATURE_NAME_LIST_REQUEST = 'FEATURE_NAME_LIST_REQUEST';
export const FEATURE_NAME_LIST_SUCCESS = 'FEATURE_NAME_LIST_SUCCESS';
export const FEATURE_NAME_LIST_FAIL = 'FEATURE_NAME_LIST_FAIL';

export const FEATURE_NAME_INSERT_REQUEST = 'FEATURE_NAME_INSERT_REQUEST';
export const FEATURE_NAME_INSERT_SUCCESS = 'FEATURE_NAME_INSERT_SUCCESS';
export const FEATURE_NAME_INSERT_FAIL = 'FEATURE_NAME_INSERT_FAIL';

export const FEATURE_INSERT_REQUEST = 'FEATURE_INSERT_REQUEST';
export const FEATURE_INSERT_SUCCESS = 'FEATURE_INSERT_SUCCESS';
export const FEATURE_INSERT_FAIL = 'FEATURE_INSERT_FAIL';

export const FEATURE_LIST_REQUEST = 'FEATURE_LIST_REQUEST';
export const FEATURE_LIST_SUCCESS = 'FEATURE_LIST_SUCCESS';
export const FEATURE_LIST_FAIL = 'FEATURE_LIST_FAIL';

export const FEATURE_DELETE_REQUEST = 'FEATURE_DELETE_REQUEST';
export const FEATURE_DELETE_SUCCESS = 'FEATURE_DELETE_SUCCESS';
export const FEATURE_DELETE_FAIL = 'FEATURE_DELETE_FAIL';

export const CATEGORIES_LIST_REQUEST = 'CATEGORIES_LIST_REQUEST';
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS';
export const CATEGORIES_LIST_FAIL = 'CATEGORIES_LIST_FAIL';

export const SUBCATEGORIES_LIST_REQUEST = 'SUBCATEGORIES_LIST_REQUEST';
export const SUBCATEGORIES_LIST_SUCCESS = 'SUBCATEGORIES_LIST_SUCCESS';
export const SUBCATEGORIES_LIST_FAIL = 'SUBCATEGORIES_LIST_FAIL';

export const SUPPLIERS_LIST_REQUEST = 'SUPPLIERS_LIST_REQUEST';
export const SUPPLIERS_LIST_SUCCESS = 'SUPPLIERS_LIST_SUCCESS';
export const SUPPLIERS_LIST_FAIL = 'SUPPLIERS_LIST_FAIL';

export const PRODUCT_LIST_BY_CATEGORY_REQUEST = 'PRODUCT_LIST_BY_CATEGORY_REQUEST';
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_LIST_BY_CATEGORY_FAIL = 'PRODUCT_LIST_BY_CATEGORY_FAIL';

export const PRODUCT_LIST_BY_CATEGORY_ADMIN_REQUEST = 'PRODUCT_LIST_BY_CATEGORY_ADMIN_REQUEST';
export const PRODUCT_LIST_BY_CATEGORY_ADMIN_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_ADMIN_SUCCESS';
export const PRODUCT_LIST_BY_CATEGORY_ADMIN_FAIL = 'PRODUCT_LIST_BY_CATEGORY_ADMIN_FAIL';

export const PRODUCT_VISIBILITY_CHANGE_REQUEST = 'PRODUCT_VISIBILITY_CHANGE_REQUEST';
export const PRODUCT_VISIBILITY_CHANGE_SUCCESS = 'PRODUCT_VISIBILITY_CHANGE_SUCCESS';
export const PRODUCT_VISIBILITY_CHANGE_FAIL = 'PRODUCT_VISIBILITY_CHANGE_FAIL';

export const CATEGORY_PERCENTAGE_CHANGE_REQUEST = 'CATEGORY_PERCENTAGE_CHANGE_REQUEST';
export const CATEGORY_PERCENTAGE_CHANGE_SUCCESS = 'CATEGORY_PERCENTAGE_CHANGE_SUCCESS';
export const CATEGORY_PERCENTAGE_CHANGE_FAIL = 'CATEGORY_PERCENTAGE_CHANGE_FAIL';

export const FEATURE_TITLES_BY_CATEGORY_REQUEST = 'FEATURE_TITLES_BY_CATEGORY_REQUEST';
export const FEATURE_TITLES_BY_CATEGORY_SUCCESS = 'FEATURE_TITLES_BY_CATEGORY_SUCCESS';
export const FEATURE_TITLES_BY_CATEGORY_FAIL = 'FEATURE_TITLES_BY_CATEGORY_FAIL';

export const FEATURE_NAMES_BY_CATEGORY_REQUEST = 'FEATURE_NAMES_BY_CATEGORY_REQUEST';
export const FEATURE_NAMES_BY_CATEGORY_SUCCESS = 'FEATURE_NAMES_BY_CATEGORY_SUCCESS';
export const FEATURE_NAMES_BY_CATEGORY_FAIL = 'FEATURE_NAMES_BY_CATEGORY_FAIL';

export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST';
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS';
export const GET_FEATURES_FAIL = 'GET_FEATURES_FAIL';

export const SENDING_LIST_REQUEST = 'SENDING_LIST_REQUEST';
export const SENDING_LIST_SUCCESS = 'SENDING_LIST_SUCCESS';
export const SENDING_LIST_FAIL = 'SENDING_LIST_FAIL';

export const EDIT_SENDING_METHOD_REQUEST = 'EDIT_SENDING_METHOD_REQUEST';
export const EDIT_SENDING_METHOD_SUCCESS = 'EDIT_SENDING_METHOD_SUCCESS';
export const EDIT_SENDING_METHOD_FAIL = 'EDIT_SENDING_METHOD_FAIL';

export const ADD_SENDING_METHOD_REQUEST = 'ADD_SENDING_METHOD_REQUEST';
export const ADD_SENDING_METHOD_SUCCESS = 'ADD_SENDING_METHOD_SUCCESS';
export const ADD_SENDING_METHOD_FAIL = 'ADD_SENDING_METHOD_FAIL';

export const REMOVE_SENDING_METHOD_REQUEST = 'REMOVE_SENDING_METHOD_REQUEST';
export const REMOVE_SENDING_METHOD_SUCCESS = 'REMOVE_SENDING_METHOD_SUCCESS';
export const REMOVE_SENDING_METHOD_FAIL = 'REMOVE_SENDING_METHOD_FAIL';

export const ADMIN_PAYMENT_LIST_REQUEST = 'ADMIN_PAYMENT_LIST_REQUEST';
export const ADMIN_PAYMENT_LIST_SUCCESS = 'ADMIN_PAYMENT_LIST_SUCCESS';
export const ADMIN_PAYMENT_LIST_FAIL = 'ADMIN_PAYMENT_LIST_FAIL';

export const EDIT_ADMIN_PAYMENT_LIST_REQUEST = 'EDIT_ADMIN_PAYMENT_LIST_REQUEST';
export const EDIT_ADMIN_PAYMENT_LIST_SUCCESS = 'EDIT_ADMIN_PAYMENT_LIST_SUCCESS';
export const EDIT_ADMIN_PAYMENT_LIST_FAIL = 'EDIT_ADMIN_PAYMENT_LIST_FAIL';

export const ADD_ADMIN_PAYMENT_LIST_REQUEST = 'ADD_ADMIN_PAYMENT_LIST_REQUEST';
export const ADD_ADMIN_PAYMENT_LIST_SUCCESS = 'ADD_ADMIN_PAYMENT_LIST_SUCCESS';
export const ADD_ADMIN_PAYMENT_LIST_FAIL = 'ADD_ADMIN_PAYMENT_LIST_FAIL';

export const REMOVE_ADMIN_PAYMENT_LIST_REQUEST = 'REMOVE_ADMIN_PAYMENT_LIST_REQUEST';
export const REMOVE_ADMIN_PAYMENT_LIST_SUCCESS = 'REMOVE_ADMIN_PAYMENT_LIST_SUCCESS';
export const REMOVE_ADMIN_PAYMENT_LIST_FAIL = 'REMOVE_ADMIN_PAYMENT_LIST_FAIL';

export const COMPATIBILITIES_BY_CATEGORY_REQUEST = 'COMPATIBILITIES_BY_CATEGORY_REQUEST';
export const COMPATIBILITIES_BY_CATEGORY_SUCCESS = 'COMPATIBILITIES_BY_CATEGORY_SUCCESS';
export const COMPATIBILITIES_BY_CATEGORY_FAIL = 'COMPATIBILITIES_BY_CATEGORY_FAIL';

export const COMPATIBILITY_COMPANIES_LIST_REQUEST = 'COMPATIBILITY_COMPANIES_LIST_REQUEST';
export const COMPATIBILITY_COMPANIES_LIST_SUCCESS = 'COMPATIBILITY_COMPANIES_LIST_SUCCESS';
export const COMPATIBILITY_COMPANIES_LIST_FAIL = 'COMPATIBILITY_COMPANIES_LIST_FAIL';

export const COMPATIBILITY_MODELS_LIST_REQUEST = 'COMPATIBILITY_MODELS_LIST_REQUEST';
export const COMPATIBILITY_MODELS_LIST_SUCCESS = 'COMPATIBILITY_MODELS_LIST_SUCCESS';
export const COMPATIBILITY_MODELS_LIST_FAIL = 'COMPATIBILITY_MODELS_LIST_FAIL';

export const INSERT_COMPATIBILITY_COMPANY_REQUEST = 'INSERT_COMPATIBILITY_COMPANY_REQUEST';
export const INSERT_COMPATIBILITY_COMPANY_SUCCESS = 'INSERT_COMPATIBILITY_COMPANY_SUCCESS';
export const INSERT_COMPATIBILITY_COMPANY_FAIL = 'INSERT_COMPATIBILITY_COMPANY_FAIL';

export const INSERT_COMPATIBILITY_MODEL_REQUEST = 'INSERT_COMPATIBILITY_MODEL_REQUEST';
export const INSERT_COMPATIBILITY_MODEL_SUCCESS = 'INSERT_COMPATIBILITY_MODEL_SUCCESS';
export const INSERT_COMPATIBILITY_MODEL_FAIL = 'INSERT_COMPATIBILITY_MODEL_FAIL';

export const INSERT_PRODUCT_COMPATIBILITY_REQUEST = 'INSERT_PRODUCT_COMPATIBILITY_REQUEST';
export const INSERT_PRODUCT_COMPATIBILITY_SUCCESS = 'INSERT_PRODUCT_COMPATIBILITY_SUCCESS';
export const INSERT_PRODUCT_COMPATIBILITY_FAIL = 'INSERT_PRODUCT_COMPATIBILITY_FAIL';

export const DELETE_PRODUCT_COMPATIBILITY_REQUEST = 'DELETE_PRODUCT_COMPATIBILITY_REQUEST';
export const DELETE_PRODUCT_COMPATIBILITY_SUCCESS = 'DELETE_PRODUCT_COMPATIBILITY_SUCCESS';
export const DELETE_PRODUCT_COMPATIBILITY_FAIL = 'DELETE_PRODUCT_COMPATIBILITY_FAIL';

export const PRODUCT_COMPATIBILITIES_REQUEST = 'PRODUCT_COMPATIBILITIES_REQUEST';
export const PRODUCT_COMPATIBILITIES_SUCCESS = 'PRODUCT_COMPATIBILITIES_SUCCESS';
export const PRODUCT_COMPATIBILITIES_FAIL = 'PRODUCT_COMPATIBILITIES_FAIL';

export const GET_PRODUCT_HISTORY_REQUEST = 'GET_PRODUCT_HISTORY_REQUEST';
export const GET_PRODUCT_HISTORY_SUCCESS = 'GET_PRODUCT_HISTORY_SUCCESS';
export const GET_PRODUCT_HISTORY_FAIL = 'GET_PRODUCT_HISTORY_FAIL';

export const GET_PRODUCT_BY_NAME_ADMIN_REQUEST = 'GET_PRODUCT_BY_NAME_ADMIN_REQUEST';
export const GET_PRODUCT_BY_NAME_ADMIN_SUCCESS = 'GET_PRODUCT_BY_NAME_ADMIN_SUCCESS';
export const GET_PRODUCT_BY_NAME_ADMIN_FAIL = 'GET_PRODUCT_BY_NAME_ADMIN_FAIL';
