export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT_REQUEST = 'USER_SIGNOUT_REQUEST';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_SIGNOUT_FAIL = 'USER_SIGNOUT_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SAVE_ACCOUNT_INFO_REQUEST = 'USER_ACCOUNT_INFO_REQUEST';
export const USER_SAVE_ACCOUNT_INFO_SUCCESS = 'USER_ACCOUNT_INFO_SUCCESS';
export const USER_SAVE_ACCOUNT_INFO_FAIL = 'USER_ACCOUNT_INFO_FAIL';

export const USER_ACCOUNT_ADDRESS_REQUEST = 'USER_ACCOUNT_ADDRESS_REQUEST';
export const USER_ACCOUNT_ADDRESS_SUCCESS = 'USER_ACCOUNT_ADDRESS_SUCCESS';
export const USER_ACCOUNT_ADDRESS_FAIL = 'USER_ACCOUNT_ADDRESS_FAIL';

export const USER_PASSWORD_CHANGE_REQUEST = 'USER_PASSWORD_CHANGE_REQUEST';
export const USER_PASSWORD_CHANGE_SUCCESS = 'USER_PASSWORD_CHANGE_SUCCESS';
export const USER_PASSWORD_CHANGE_FAIL = 'USER_PASSWORD_CHANGE_FAIL';

export const ADD_TO_NEWSLETTER_REQUEST = 'ADD_TO_NEWSLETTER_REQUEST';
export const ADD_TO_NEWSLETTER_SUCCESS = 'ADD_TO_NEWSLETTER_SUCCESS';
export const ADD_TO_NEWSLETTER_FAIL = 'ADD_TO_NEWSLETTER_FAIL';

export const REMOVE_FROM_NEWSLETTER_REQUEST = 'REMOVE_FROM_NEWSLETTER_REQUEST';
export const REMOVE_FROM_NEWSLETTER_SUCCESS = 'REMOVE_FROM_NEWSLETTER_SUCCESS';
export const REMOVE_FROM_NEWSLETTER_FAIL = 'REMOVE_FROM_NEWSLETTER_FAIL';

export const DELETE_USER_ACCOUNT_REQUEST = 'DELETE_USER_ACCOUNT_REQUEST';
export const DELETE_USER_ACCOUNT_SUCCESS = 'DELETE_USER_ACCOUNT_SUCCESS';
export const DELETE_USER_ACCOUNT_FAIL = 'DELETE_USER_ACCOUNT_FAIL';

export const ADMINS_LIST_REQUEST = 'ADMINS_LIST_REQUEST';
export const ADMINS_LIST_SUCCESS = 'ADMINS_LIST_SUCCESS';
export const ADMINS_LIST_FAIL = 'ADMINS_LIST_FAIL';

export const INSERT_ADMIN_REQUEST = 'INSERT_ADMIN_REQUEST';
export const INSERT_ADMIN_SUCCESS = 'INSERT_ADMIN_SUCCESS';
export const INSERT_ADMIN_FAIL = 'INSERT_ADMIN_FAIL';

export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';